/**
 * Payslip Records — durable, searchable record keeping for every payslip
 * generated by the Payroll System, keyed per (employee, month, year).
 *
 * A record captures a full snapshot of the employee's payroll data at the
 * moment the payslip was generated (export / send / batch export), so a
 * historical payslip can be re-previewed or re-downloaded EXACTLY as it was
 * issued even after the live payroll row is edited. Records live in the
 * station-scoped cloud key `payroll_payslip_records` (compressed app_kv
 * envelope) — cross-device, no schema changes.
 */

/** Cloud key (station-scoped) holding the payslip record list. */
export const PAYSLIP_RECORDS_KEY = "payroll_payslip_records";

/** Hard cap so the cloud row stays small (oldest records roll off). */
export const PAYSLIP_RECORDS_CAP = 1000;

/**
 * Minimal employee snapshot needed to regenerate the payslip PDF later.
 * Structurally compatible with the PayrollSystem `Employee` interface — the
 * full employee object is stored so nothing is lost, but only these fields
 * are relied upon.
 */
export interface PayslipEmployeeSnapshot {
  id?: number;
  no?: string;
  firstName?: string;
  lastName?: string;
  fullName?: string;
  employeeId?: string;
  role?: string;
  department?: string;
  basicSalary?: number;
  sha?: number;
  nssf?: number;
  advance?: number;
  customDeductions?: {
    typeId: string;
    amount: number;
    mode?: "fixed" | "percent" | "describe";
  }[];
  earnings?: {
    typeId: string;
    amount: number;
    mode?: "fixed" | "percent" | "describe";
  }[];
  netPay?: number;
  paymentMethod?: "bank" | "cash";
  bank?: string;
  bankCode?: string;
  idNo?: string;
  kraPin?: string;
  shaNo?: string;
  nssfNo?: string;
  bankAccount?: string;
  phone?: string;
  email?: string;
  employmentDate?: string;
  notes?: string;
}

export interface PayslipRecord {
  /** Stable unique id: `pr_<employeeId>_<periodKey>`. */
  id: string;
  employeeId: string;
  employeeName: string;
  /** Machine-sortable period, e.g. "2026-08". */
  periodKey: string;
  /** Human period, e.g. "August 2026". */
  periodLabel: string;
  month: number; // 1-12
  year: number;
  grossPay: number;
  totalDeductions: number;
  netPay: number;
  /** How this record came to exist. */
  source: "export" | "send" | "batch";
  /** ISO timestamp of (re)generation. */
  generatedAt: string;
  /** Public storage URL if the PDF was uploaded during a send. */
  fileUrl?: string;
  /** Full payroll snapshot for exact regeneration. */
  employee: PayslipEmployeeSnapshot;
}

/** "August 2026" from numeric month/year. */
export function payrollPeriodLabel(month: number, year: number): string {
  const safeMonth = Math.min(12, Math.max(1, Math.trunc(month) || 1));
  const name = new Date(2023, safeMonth - 1).toLocaleString("default", {
    month: "long",
  });
  return `${name} ${year}`;
}

/** "2026-08" from numeric month/year — sortable, used for dedupe keys. */
export function payrollPeriodKey(month: number, year: number): string {
  const safeMonth = Math.min(12, Math.max(1, Math.trunc(month) || 1));
  return `${year}-${String(safeMonth).padStart(2, "0")}`;
}

/** Stable record id for one (employee, period) pair. */
export function payslipRecordId(employeeId: string, periodKey: string): string {
  return `pr_${employeeId || "unknown"}_${periodKey}`;
}

export interface PayslipRecordInput {
  employeeId: string;
  employeeName: string;
  month: number;
  year: number;
  grossPay: number;
  totalDeductions: number;
  netPay: number;
  source: PayslipRecord["source"];
  fileUrl?: string;
  employee: PayslipEmployeeSnapshot;
}

export function buildPayslipRecord(input: PayslipRecordInput): PayslipRecord {
  const periodKey = payrollPeriodKey(input.month, input.year);
  return {
    id: payslipRecordId(input.employeeId, periodKey),
    employeeId: input.employeeId,
    employeeName: input.employeeName,
    periodKey,
    periodLabel: payrollPeriodLabel(input.month, input.year),
    month: input.month,
    year: input.year,
    grossPay: input.grossPay,
    totalDeductions: input.totalDeductions,
    netPay: input.netPay,
    source: input.source,
    generatedAt: new Date().toISOString(),
    fileUrl: input.fileUrl,
    employee: input.employee,
  };
}

/**
 * Upsert a record into the list — one record per (employee, period); a
 * regeneration refreshes the snapshot + timestamp instead of duplicating.
 * Newest first; capped at PAYSLIP_RECORDS_CAP.
 */
export function upsertPayslipRecord(
  list: PayslipRecord[],
  record: PayslipRecord,
): PayslipRecord[] {
  const idx = list.findIndex((r) => r.id === record.id);
  const next =
    idx >= 0
      ? list.map((r) => (r.id === record.id ? record : r))
      : [record, ...list];
  next.sort((a, b) => b.generatedAt.localeCompare(a.generatedAt));
  return next.slice(0, PAYSLIP_RECORDS_CAP);
}

export interface PayslipRecordFilter {
  /** Free-text match against employee name / id. */
  search?: string;
  /** 1-12, undefined = any. */
  month?: number;
  year?: number;
}

export function filterPayslipRecords(
  records: PayslipRecord[],
  filter: PayslipRecordFilter,
): PayslipRecord[] {
  const q = (filter.search || "").trim().toLowerCase();
  return records.filter((r) => {
    if (filter.month && r.month !== filter.month) return false;
    if (filter.year && r.year !== filter.year) return false;
    if (!q) return true;
    return (
      r.employeeName.toLowerCase().includes(q) ||
      r.employeeId.toLowerCase().includes(q) ||
      r.periodLabel.toLowerCase().includes(q)
    );
  });
}

/** Distinct years present in the records (for the year filter dropdown). */
export function payslipRecordYears(records: PayslipRecord[]): number[] {
  return [...new Set(records.map((r) => r.year))].sort((a, b) => b - a);
}
